add_newline = false
command_timeout = 1000

format = """
$character\
$shell\
[](fg:white bg:bright-black)\
[█](fg:bright-black bg:black)\
$directory\
[█](fg:bright-black bg:black)\
[$git_branch\
$git_state\
$git_status](bold bg:black fg:white)\
$fill\
[](fg:bright-yellow bg:black)\
[  ](fg:bright-yellow bg:black inverted)\
[](fg:yellow bg:bright-yellow)\
[](fg:bright-black bg:yellow)\
$hostname\
$line_break\
[❯ ](bold yellow)"""

[shell]
disabled = false
bash_indicator = "BASH"
zsh_indicator = "ZSH"
fish_indicator = "FISH"
format = "[█](fg:bright-white bg:black)[ $indicator](fg:bright-white bg:black inverted bold)[](fg:bright-white bg:white)"

[character]
format = "$symbol"
error_symbol = "[█](fg:red bg:black)[ ERROR](fg:red bg:black inverted bold)[](fg:red bg:white)"
#success_symbol = "[█](fg:bright-white bg:black)[ PROMPT](fg:bright-white bg:black inverted bold)[](fg:bright-white bg:white)"
success_symbol = ""

[fill]
symbol = ' '
style = 'bg:black'

[package]
disabled = false

[cmd_duration]
min_time = 1000
show_milliseconds = false
disabled = false
format="[󰞌 $duration ]($style)"
style="bold bg:black"

[directory]
truncation_length = 5
format = "[󰉋 $path]($style)[$lock_symbol]($lock_style)"
style = "bold fg:bright-white bg:bright-black"
read_only = "🔒"
read_only_style= "bold white"

[username]
show_always = true
style_user = "bg:bright-black"
style_root = "bg:bright-black"
format = '[ $user ]($style)'

[hostname] 
format = "[$hostname ]($style)"
ssh_only = false
trim_at = ".companyname.com"
disabled = false
style = "fg:white bg:bright-black "

[git_commit]
commit_hash_length = 8
style = "bold white"

[status]
style = "bg:transparent"
symbol = "💥 "
format = '($style)'
disabled = false

[git_branch]
format = " 󰘬 $branch"
style = "bold fg:bright-black bg:black"

[git_status]
format = " $conflicted$untracked$modified$staged$renamed$deleted$ahead_behind$stashed"
style = "cyan"
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "cyan"
